
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-tls
spec:
  dnsNames:
    - "bvkme.lan.ping6.nl"
    - "bvkme.p6lab.net"
    - "www.bvk.me"
    - "bvk.me"
    - "www.ping6.nl"
    - "ping6.nl"
  secretName: website-tls
  issuerRef:
    name: letsencrypt-cloudflare-issuer
    kind: ClusterIssuer
