apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;

        absolute_redirect off;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        add_header Content-Security-Policy "frame-ancestors 'self';block-all-mixed-content;default-src 'self';script-src 'self' 'sha256-mC5lwOEBZZZXJoN3sDvzxnxAdNIEKujq9NSXgmhc4HM=' 'sha256-iIf+c/EMxKD/FXoUDy0YsZ3mE+JhzPsmR+aVbrjkdwM=' 'report-sample' 'unsafe-inline' https://static.cloudflareinsights.com;style-src 'self' 'sha256-qOUXaVhMwjZmqqi5+W6pNR5QK3wCiUgqOEkYBZAaaG4=' 'sha256-oP0lUXNLVta8iZrBpndNfoYaLUqtOFUepmmF7cSSmKY=' 'sha256-+YWRMZ88jMyO7jVlBA52tZADiPobPIUA8LAWee68Fvs=' 'sha256-umDNa5+wEukAb2uOcsXGyk7fH4cAtGIdY/LxD4cAOWs=' 'sha256-z1feagJIYQX5xSgilbQgdvBTP2Vm7MYfTpWz4KU5sxs=' 'sha256-wfFRBRN9VtnoKyjFp7nESoyL5GicNVcIrkvfmAPxv1s=' 'sha256-AIsMoEZ2AFYSNPqPHAPTfeQBkBx0uwe/S138h7oBgqk=' 'sha256-mG3x7kPh9Tg2tpVcQvu9qSUpO0QuLZP1E4wDzpTKrMc=' 'sha256-IcqGb0TAbH6mKQhvd8hBx2FAalfysv4UbOSlrgEnNqs=' 'report-sample' 'unsafe-inline';object-src 'none';frame-src 'self';child-src 'self';img-src 'self' data:;font-src 'self';connect-src 'self' cloudflareinsights.com;manifest-src 'self';base-uri 'self';form-action 'self';media-src 'self';prefetch-src 'self';worker-src 'self';"

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }