apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;

        absolute_redirect off;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'static.cloudflareinsights.com'; script-src-elem 'self' 'unsafe-inline'; script-src-attr 'self' 'unsafe-inline'; connect-src 'self' 'cloudflareinsights.com'; frame-ancestors 'self'; form-action 'self'";

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }