apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  template:
    metadata:
      labels:
        app: website
        version: "v1.0"
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v3.6.6
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: config
        volumeMounts:
        - name: docusaurus
          mountPath: /tmp/git
      - name: docusaurus
        image: node:18.16.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: config
        volumeMounts:
        - name: docusaurus
          mountPath: /tmp/src         
        - name: html
          mountPath: /tmp/html         
        command:
          - /bin/sh
          - -c
          - |
            cd /tmp/src/bvkme-website.git/website
            npm install
            npm run build
            cd build
            cp -r . /tmp/html
            sleep infinity
      - name: nginx
        image: nginxinc/nginx-unprivileged
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: config
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html           
      volumes:
        - name: docusaurus
          emptyDir: {}
        - name: html
          emptyDir: {}
