apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: bvkme
  replicas: 1
  template:
    metadata:
      labels:
        app: bvkme
        version: "v1.0"
    spec:
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync:v3.1.3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: bvkme-config
        volumeMounts:
        - name: docusaurus
          mountPath: /tmp/git
      volumes:
        - name: docusaurus
          emptyDir: {}
            