
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: website-ingress
#   namespace: bvkme
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: bvkme.lan.ping6.nl
#     http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: website-service
#                 port:
#                   number: 8080
#   - host: bvk.me
#     http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: website-service
#                 port:
#                   number: 8080                  
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress-https
  namespace: bvkme
spec:
  ingressClassName: nginx
  rules:
  - host: bvkme.lan.ping6.nl
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-service
                port:
                  number: 8080
  - host: bvk.me
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-service
                port:
                  number: 8080             
  - host: www.bvk.me
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-service
                port:
                  number: 8080       
  - host: www.ping6.nl
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-service
                port:
                  number: 8080         
  - host: ping6.nl
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-service
                port:
                  number: 8080                                                                      
  tls:
  - hosts:
      - bvkme.lan.ping6.nl
      - bvk.me
      - www.bvk.me
      - ping6.nl
      - www.ping6.nl
    secretName:
      website-tls
