apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http-website
  selector:
    app: website
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    app: proxy
spec:
  type: ClusterIP
  ports:
  - port: 5000
    name: http-proxy
  selector:
    app: proxy
