name: Build Container Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "website/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "website/**"

  workflow_dispatch:

env:
  REGISTRY: harbor.lan.ping6.nl
  PROJECT: library
  FOLDER: bvkme
  NAME: website
  TAG: latest

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build and Push Images
        run: |
          cd $GITHUB_WORKSPACE
          yarn --no-progress --cwd website install
          yarn --no-progress --cwd website build
          docker buildx build --push --platform linux/arm64,linux/amd64 --tag $REGISTRY/$PROJECT/$FOLDER/$NAME:$TAG -f Dockerfile-website .
  restart_website:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Restart Deployment Website
        run: |
          kubectl --kubeconfig ~/.kube/pi-cluster.yaml -n bvkme rollout restart deployment website



